# Generated by Django 4.0.2 on 2023-10-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0003_coachingstudents'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default='Test', max_length=100),
        ),
    ]
