# Generated by Django 4.0.2 on 2023-10-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0006_test_obtained_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresultdetails',
            old_name='answer',
            new_name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='testresultdetails',
            name='coaching',
        ),
        migrations.RemoveField(
            model_name='testresultdetails',
            name='question_paper',
        ),
        migrations.RemoveField(
            model_name='testresultdetails',
            name='subject',
        ),
        migrations.AddField(
            model_name='testresultdetails',
            name='user_answer',
            field=models.CharField(default='not_get', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testresultdetails',
            name='is_correct',
            field=models.CharField(choices=[('correct', 'Correct'), ('incorrect', 'Incorrect'), ('not_answered', 'Not Answered')], default='not_answered', max_length=100),
        ),
    ]
